
import "./globals.css";
import Navbar from "./navbar/page";


export const metadata = {
  title: "Karavali Yatra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
      </body>
    </html>
  );
}
